name: toast_view
description: A pure flutter toast library, support custom style/widget, easy achieve the same effect with native toasts.
homepage: https://github.com/arzrasel/flutter-toast-view
version: 0.0.1

environment:
  sdk: ">=2.16.0-80.1.beta <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
